services:
  trtexec:
    image: nvcr.io/nvidia/tensorrt:25.10-py3
    container_name: blip2-tensorrt-converter
    volumes:
      - ./model:/workspace/model
      - ./output:/workspace/output
      - ./scripts/convert_to_engine.sh:/workspace/convert_to_engine.sh
    working_dir: /workspace
    command: bash convert_to_engine.sh
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        limits:
          memory: 240G
        reservations:
          memory: 200G
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

